local function shown(p)
 local rows={};for _,b in ipairs(p.rows) do if b:IsShown() then rows[#rows+1]=b.entry end end;return rows
end
test('Hide Locked defaults off with independent controls beside each heading',function()
 local R=reset();R:Lock('A:101');R:Lock('T:201')
 for _,kind in ipairs({'ability','talent'}) do
  local p=R.window.panels[kind]
  assert(not R:IsHidingLocked(kind) and not p.hideLockedToggle:GetChecked())
  assert(p.hideLockedText:GetText()=='Hide Locked' and p.hideLockedControl.point[2]==116 and p.hideLockedControl.point[3]==-10)
  assert(#shown(p)==(kind=='ability' and 2 or 1))
 end
 assert(#calls==0)
end)
test('each Hide Locked checkbox hides only its own protected rows and preserves the locks',function()
 local R=reset();local a,t=R.window.panels.ability,R.window.panels.talent
 R:Lock('A:101');R:Lock('T:201');a.hideLockedToggle.scripts.OnClick()
 assert(R:IsHidingLocked('ability') and not R:IsHidingLocked('talent'))
 assert(#shown(a)==1 and shown(a)[1].key=='A:102' and #shown(t)==1)
 assert(a.count:GetText()=='1 / 2 shown' and t.count:GetText()=='1 learned')
 t.hideLockedToggle.scripts.OnClick();assert(#shown(t)==0 and t.empty:IsShown())
 assert(R:Locks(R.spec)['A:101'] and R:Locks(R.spec)['T:201'])
 a.hideLockedControl.scripts.OnMouseUp(a.hideLockedControl,'LeftButton')
 assert(#shown(a)==2 and a.rows[1].lock:IsShown() and R:IsHidingLocked('talent') and #calls==0)
end)
test('saved hide choices survive reinitialization, reopen and refresh without resetting layout or history',function()
 local R=reset();R:Lock('A:101');R:ToggleHideLocked('ability')
 local db=R.db;db.width=1020;db.height=740;db.x=32;db.y=-5
 local history=R.character.history;local locks=R:Locks(R.spec)
 R:InitializeDB(db);R.window:Hide();R.window:Show();R:Refresh()
 assert(R:IsHidingLocked('ability') and not R:IsHidingLocked('talent') and #shown(R.window.panels.ability)==1)
 assert(db.width==1020 and db.height==740 and db.x==32 and db.y==-5 and history==R.character.history and locks==R:Locks(R.spec))
 assert(#calls==0)
end)
test('Hide Locked combines with literal case-insensitive search without revealing protected matches',function()
 local R=reset();local a=R.window.panels.ability
 R:Lock('A:101');R:ToggleHideLocked('ability');a.search:SetText('SPELL 101');R:Render()
 assert(#shown(a)==0 and a.empty:GetText():find('No unlocked abilities match',1,true))
 a.search:SetText('SPELL 102');R:Render();assert(#shown(a)==1 and shown(a)[1].key=='A:102')
 a.search:SetText('Spell 10');R:Render();assert(#shown(a)==1)
 R:ToggleHideLocked('ability');assert(#shown(a)==2 and R:Locks(R.spec)['A:101'])
 a.search:SetText('[');R:Render();assert(#shown(a)==0 and a.empty:IsShown() and #calls==0)
end)
test('locking an entry immediately hides it; showing and unlocking restores it without spending scrolls',function()
 local R=reset();local a=R.window.panels.ability;R:ToggleHideLocked('ability')
 local b=a.rows[1];R:Toggle('A:101');b.scripts.OnClick(b,'RightButton')
 assert(R:Locks(R.spec)['A:101'] and not R.selected['A:101'] and #shown(a)==1)
 R:ToggleHideLocked('ability');b=a.rows[1];b.scripts.OnClick(b,'RightButton')
 assert(popup.name=='GRR_UNLOCK' and R:Locks(R.spec)['A:101'])
 StaticPopupDialogs.GRR_UNLOCK.OnAccept({},popup.data);R:ToggleHideLocked('ability')
 assert(not R:Locks(R.spec)['A:101'] and #shown(a)==2 and #calls==0 and scrollCounts[640]==10)
end)
test('all-locked and no-learned empty states explain how to restore the list',function()
 local R=reset();local a,t=R.window.panels.ability,R.window.panels.talent
 R:Lock('A:101');R:Lock('A:102');R:Lock('T:201');R:ToggleHideLocked('ability');R:ToggleHideLocked('talent')
 assert(a.empty:GetText()=='All abilities are locked.\nUncheck Hide Locked to show them.')
 assert(t.empty:GetText()=='All talents are locked.\nUncheck Hide Locked to show them.' and a.count:GetText()=='0 / 2 shown')
 R:ToggleHideLocked('talent');assert(not t.empty:IsShown() and #shown(t)==1)
 R.rows={};R:Render();assert(a.empty:GetText()=='No learned abilities to display.' and t.empty:GetText()=='No learned talents to display.' and #calls==0)
end)
test('filter toggles never edit selection, original rows, history, pending requests or the running queue',function()
 local R=reset();R:Lock('T:201');R:Toggle('A:101');R:Toggle('A:102');R:Start('ability')
 local pending,queue,rows,byKey,selection,history=R.pending,R.queue,R.rows,R.byKey,R.selected,R.character.history
 local remaining=queue[1];local beforeCalls=#calls;local budget=R:Totals().ability
 R:ToggleHideLocked('ability');R:ToggleHideLocked('talent');R:ToggleHideLocked('ability')
 assert(R.running and R.pending==pending and R.queue==queue and queue[1]==remaining)
 assert(R.rows==rows and R.byKey==byKey and R.selected==selection and R.selected['A:102'])
 assert(history==R.character.history and R:Totals().ability==budget and #calls==beforeCalls and R:Locks(R.spec)['T:201'])
 R:Stop('test complete');R.pending=nil
end)
test('filter toggles reset only their column; ordinary renders preserve scroll and clamp shorter results',function()
 local R=reset();local a,t=R.window.panels.ability,R.window.panels.talent
 known={};for i=101,130 do known[#known+1]=i end
 R:Refresh();a.scroll:SetHeight(162);t.scroll:SetHeight(54)
 a.scroll:SetVerticalScroll(432);R:Render();assert(a.scroll:GetVerticalScroll()==432)
 t.scroll:SetVerticalScroll(0);R:ToggleHideLocked('talent');assert(a.scroll:GetVerticalScroll()==432)
 for _,entry in ipairs(R.rows) do if entry.kind=='ability' then R:Locks(R.spec)[entry.key]=true end end
 R:ToggleHideLocked('ability');assert(a.scroll:GetVerticalScroll()==0 and #shown(a)==0)
 R:ToggleHideLocked('ability');a.scroll:SetVerticalScroll(432);a.search:SetText('Spell 101');R:Render()
 assert(a.scroll:GetVerticalScroll()==0 and #shown(a)==1)
 a.search:SetText('');R:Render();R:ToggleHideLocked('ability');R:Unlock('A:101',R.spec);assert(#shown(a)==1 and a.scroll:GetVerticalScroll()==0)
 assert(#calls==0)
end)
test('hidden rows clear stale tooltips and cannot expose the previous entry through recycled buttons',function()
 local R=reset();local a=R.window.panels.ability;local b=a.rows[1]
 R:Lock('A:101');b.scripts.OnEnter(b);assert(GameTooltip:IsShown() and GameTooltip:IsOwned(b))
 R:ToggleHideLocked('ability');assert(not GameTooltip:IsShown() and b.entry.key=='A:102')
 R:Lock('A:102');assert(not b:IsShown() and b.entry==nil)
 b.scripts.OnClick(b,'LeftButton');b.scripts.OnEnter(b)
 assert(not GameTooltip:IsShown() and not next(R.selected) and #calls==0)
end)
test('Hide Locked follows active-spec protections without carrying another spec lock across',function()
 local R=reset();R:Lock('A:101');R:ToggleHideLocked('ability')
 assert(#shown(R.window.panels.ability)==1)
 spec=2;R:Refresh();assert(#shown(R.window.panels.ability)==2 and R:IsHidingLocked('ability'))
 assert(not R:Locks(R.spec)['A:101'] and R:Locks('specialization:1')['A:101'])
 spec=1;R:Refresh();assert(#shown(R.window.panels.ability)==1 and #calls==0)
end)
test('unknown filter kinds and invalid legacy preferences cannot affect protected entries',function()
 local R=reset();R:Lock('A:101');R.db.hideLocked='legacy';R:Render()
 assert(not R:IsHidingLocked('ability') and #shown(R.window.panels.ability)==2)
 R:ToggleHideLocked('wrong');assert(R.db.hideLocked=='legacy')
 R:ToggleHideLocked('ability');assert(R:IsHidingLocked('ability') and #shown(R.window.panels.ability)==1)
 assert(R:Locks(R.spec)['A:101'] and #calls==0)
end)
